name: walnuts tests

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch: {}

env:
  CACHE_VERSION: 1

# only run one copy per PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (${{matrix.cfg.os}}/${{matrix.cfg.compilerpp}})
    runs-on: ${{matrix.cfg.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - os: windows
            compiler: cl.exe
            compilerpp: cl.exe
          - os: windows
            compiler: gcc.exe
            compilerpp: g++.exe
          - os: ubuntu
            compiler: gcc
            compilerpp: g++
          - os: macos
            compiler: clang
            compilerpp: clang++

    steps:
      - name: Check out github
        uses: actions/checkout@v4

      - name: build caching
        uses: actions/cache@v4
        id: deps-cache
        with:
          path: ./build/deps/
          key: ${{ runner.os }}-${{ matrix.cfg.compiler }}-deps-${{ hashFiles('**/CMakeLists.txt') }}-v${{ env.CACHE_VERSION }}

      - uses: ilammy/msvc-dev-cmd@v1
        if: matrix.cfg.compiler == 'cl.exe'

      - name: Build
        run: |
          mkdir -p build/
          cmake -S . -B build/ -DWALNUTS_BUILD_TESTS=ON -DWALNUTS_BUILD_DOCS=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja -DCMAKE_C_COMPILER=${{ matrix.cfg.compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.cfg.compilerpp }}
          cmake --build build/ --parallel 4


      - name: Run examples
        run: |
          cd build/
          ./test_nuts
        shell: bash

      - name: Test
        run: |
          cd build/
          ctest --output-on-failure --parallel 4 --repeat until-pass:2
        shell: bash
